words:
  - appscheme
  - batcave
  - camelize
  - codepaths
  - deeplink
  - deeplinking
  - finstrong
  - mxenabled
  - mxmobilewidgetsdkdemo
  - mxwidgetsdkdemo
  - ngrx
  - tsbuildinfo

ignorePaths:
  - cspell.config.yaml
  - docs/widget_callback_props.md
  - example/.flowconfig
  - example/.gitignore
  - example/android/**
  - example/ios/**
