name: Build Example App

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - name: Run npm ci (sdk)
      run: npm ci

    - name: Run npm ci (app)
      run: npm ci
      working-directory: example

    - name: Create config file
      working-directory: example
      run: |
        echo '{ "proxy": "http://fakeserver.com" }' > config.json

    - run: npm run build
      working-directory: example
